version: '3.8'

services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      cache_from:
        - ghcr.io/${GITHUB_REPOSITORY:-yourusername/comfyui}:cache
      args:
        BASE_IMAGE: ghcr.io/${GITHUB_REPOSITORY:-yourusername/comfyui}:base
    image: comfyui:latest
    ports:
      - "8188:8188"
      - "8888:8888"
    volumes:
      - ./models:/workspace/models
      - ./output:/workspace/output
      - ./workflows:/workspace/workflows
    environment:
      - HF_HOME=/workspace
      - HF_HUB_ENABLE_HF_TRANSFER=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]